version: '3.6'
services:
  api:
    image: 20scoops/ruby-cypress
    container_name: e2e api
    volumes:
      - ./cypress/results:/usr/src/app/cypress/results
    command: >
      bash -c "  
      yarn cypress run --spec cypress/integration/**/*.spec.js"
  frontend:
    image: 20scoops/ruby-cypress
    container_name: e2e frontend
    volumes:
      - ./cypress/results:/usr/src/app/cypress/results
    command: >
      bash -c "  
      yarn cypress run --spec cypress/integration/**/*.spec.js"      
