# BASE IMAGE DOCKER
FROM cypress/browsers:node12.4.0-chrome76

#MAKE WORK DIRECTORY CYPRESS
WORKDIR /usr/src/app/

# COPY ALL IN CYPRESS TO WORK DIRECTORY
COPY . /usr/src/app/

# INSTALL YARN
CMD [ "yarn" ]