defaults: &defaults
  docker:
    - image: cypress/base:10
      environment:
        TERM: xterm
  working_directory: ~/app
  parallelism: 1
version: 2.1
jobs:
  install_and_checking:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Trigger
          command: |
            echo $cypress_external
            "curl --request POST \
            --url https://api.github.com/repos/20Scoops-CNX/procom-cypress/dispatches \
            --header 'accept: application/vnd.github.everest-preview+json' \
            --header 'authorization: Bearer 0cf42b3c8db6998faeb45b96dcff4eb44ea72d16' \
            --header 'content-type: application/json' \
            --data $json_cypress"
  version: 2
  Cypress:
    jobs:
      - install_and_checking:
          context: global-text
