defaults: &defaults
  docker:
    - image: cypress/base:10
      environment:
        TERM: xterm
  working_directory: ~/app
  parallelism: 1
version: 2.1
jobs:
  install_and_checking:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Trigger
          command: |
            curl --request POST \
            --url https://api.github.com/repos/golfzaptw/cypress-docker/dispatches \
            --header 'accept: application/vnd.github.everest-preview+json' \
            --header 'authorization: Bearer '${GITHUB_TOKEN_KEY} \
            --header 'content-type: application/json' \
            --data '{"event_type":"external_test"}'

workflows:
  version: 2
  Cypress:
    jobs:
      - install_and_checking:
          context: global-text
          filters:
            branches:
              only:
                - masters
                - dev
              ignore:
                - merge
