name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - name: build docker-compose
        run: docker-compose up
      - name: upload report
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: cypress/results/report
